name: My Starter Workflow

on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    strategy:
      matrix:
        nodeversion: [14, 16, 18, 20]
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      node: ${{ matrix.nodeversion }}

  build:
    runs-on: ubuntu-latest
    needs: call-reusable-workflow  # 如果你想让 build 在调用的任务之后执行
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy to your project.
